/*
 * main.h
 *
 *  Created on: 6-sep.-2014
 *      Author: lieven2
 */

#ifndef MAIN_H_
#define MAIN_H_

typedef enum  {
	SIG_IDLE,
	SIG_ENTRY,
	SIG_EXIT,
	SIG_INIT,
	SIG_TIMER_TICK,
	SIG_USER,
	SIG_USB_CONNECTED = SIG_USER + 1,
	SIG_USB_DISCONNECTED,
	SIG_USB_RXD,
	SIG_USB_FREE,
	SIG_MQTT_CONNECTED,
	SIG_MQTT_DISCONNECTED,
	SIG_MQTT_MESSAGE,
	SIG_MQTT_DO_PUBLISH,
	SIG_MQTT_PUBLISH_FAILED,
	SIG_MQTT_PUBLISH_OK,
	SIG_PROP_CHANGED
} Signal;

enum MqttMessageTags {
	T_ID, T_HEADER, T_TOPIC, T_MESSAGE, T_MESSAGE_ID
};

#endif /* MAIN_H_ */

